#+TITLE: Hyperlexia


readme driven development
** Starting decisions
*** Language
    ClojureScript / Clojure.

    *How come?* Functions! They're a left-module of vars acting on data! Fun to write!

*** Environment
    Figwheel + Devcards.

    *How come?* Closest we've got to a visual repl. 
    
*** Dependencies
    React via Rum.

    *How come?* It is the smallest React wrapper that I'm aware of. It is used and recommended by a mathematician doing information visualization work for the public (see, Communicating Risk talk). It is intended to be compatible with DataScript, which is a pattern of interest for me. 

*** Development
    Navigate to directory. =lein figwheel=. Now you're in the devcards build. I'll develop in this until I am getting happy with the results, and then I'll look into how to make a new figwheel build for production.

** Data Source 1

<2016-11-22 Tue>

What I want to do is download a list of likes. I'm not sure if I can do that? Wait did I install =t= on this computer? 

Shit. Well, I don't *want* to start by wrangling OAuth. 

Let's do some dumb manual shit. Open

https://twitter.com/mathpunk/likes

which requires you to be logged in. Take maybe ten minutes to open everything and copy it in right freakin' here. 

#+BEGIN_SRC txt :tangle resources/data/likes_late_november.txt

https://twitter.com/ekstasis/status/801004674035970048
https://twitter.com/leashless/status/801014346474135552
https://twitter.com/KBSpangler/status/801081463902969856
https://twitter.com/dynamicsymmetry/status/801083674221510656
https://twitter.com/whispersystems/status/801091427564294144
https://twitter.com/quinnnorton/status/801102736049770496
https://twitter.com/Lexialex/status/801110335868411904
https://twitter.com/WrrrdNrrrdGrrrl/status/801111655824273408
https://twitter.com/minhyoungsong/status/801120653726384129
https://twitter.com/newinquiry/status/801123097092833280
https://twitter.com/planetlabs/status/801127974745481216
https://twitter.com/kissane/status/801133298785329152
https://twitter.com/hautepop/status/801138208230744064
https://twitter.com/hautepop/status/801138747907731458
https://twitter.com/cnqmdi/status/801139470082985984
https://twitter.com/dunagan23/status/801139777210843140
https://twitter.com/mathpunk/likes
https://twitter.com/KevinCarson1/status/800905914123481088
https://twitter.com/TheViewFromLL2/status/800907771101270016
https://twitter.com/DevonAkmon/status/800907938412064768
https://twitter.com/familyunequal/status/800911127752249344
https://twitter.com/TheViewFromLL2/status/800914024686874633
https://twitter.com/abditum/status/800920210081345536
https://twitter.com/garrettlisi/status/800921787361918976
https://twitter.com/realscientists/status/800921883340214272
https://twitter.com/susie_c/status/800923877849210880
https://twitter.com/alan_uplc/status/800927192683266048
https://twitter.com/denormalize/status/800927743323930624
https://twitter.com/b0rk/status/800928953691230208
https://twitter.com/joanwalsh/status/800932791458394113
https://twitter.com/realscientists/status/800935368094646273
https://twitter.com/MLCzone/status/800943210885513216
https://twitter.com/jimacmcdermott/status/800949917413801984
https://twitter.com/jeffjarvis/status/800950687416913924
https://twitter.com/GeraldFitt/status/800951041424359424
https://twitter.com/TessFowler/status/800952814314733568
https://twitter.com/carolinesinders/status/800953107077218305
https://twitter.com/ameliaabreu/status/800953388993122304
https://twitter.com/daisykpgardner/status/800961932752629760
https://twitter.com/justinpickard/status/800970162413387776
https://twitter.com/livingarchitect/status/800971854504751104
https://twitter.com/starsandrobots/status/800868628811812865
https://twitter.com/HeerJeet/status/800874083369897984
https://twitter.com/KatrinaNation/status/800877980545417216
https://twitter.com/nytmedia/status/800878423010930689
https://twitter.com/leahmcelrath/status/800878498453680128
https://twitter.com/Freeyourmindkid/status/800878733850722304
https://twitter.com/pbump/status/800878833570353157
https://twitter.com/rechelon/status/800879070623862784
https://twitter.com/alyssaharad/status/800881281932226560
https://twitter.com/sarahkendzior/status/800881494524882944
https://twitter.com/moonandserpent/status/800881567119732738
https://twitter.com/alyssaharad/status/800887571232473088
https://twitter.com/ta_shepard/status/800889586465374208
https://twitter.com/anthoknees/status/800889593994194944
https://twitter.com/jessamyn/status/800894360686563328
https://twitter.com/tealtan/status/800894558578049024
https://twitter.com/lisarokusek/status/800896670296932354
https://twitter.com/robotnik/status/800896683676614656
https://twitter.com/FrankPasquale/status/800898688574951424
https://twitter.com/metasj/status/800899196031221760
https://twitter.com/inllhrprhntr/status/800899495726813184
https://twitter.com/BrendanNyhan/status/800899559006359552
https://twitter.com/FrankPasquale/status/800900595414659072
https://twitter.com/JYSexton/status/800900750717108224
https://twitter.com/Chris_arnade/status/800901419389820928
https://twitter.com/mulegirl/status/800902587079766016
https://twitter.com/fatneckbeardguy/status/800808669868765184
https://twitter.com/splcenter/status/800808843370463232
https://twitter.com/B_Meson/status/800809125911363585
https://twitter.com/B_Meson/status/800809566850035712
https://twitter.com/aurabogado/status/800809653902811137
https://twitter.com/jesseberney/status/800810510199439361
https://twitter.com/daveweigel/status/800811844025860096
https://twitter.com/BostonJoan/status/800812459074338816
https://twitter.com/paddyhirsch/status/800812742424702976
https://twitter.com/FrankLuntz/status/800813103210381314
https://twitter.com/KevinCarson1/status/800814453512142856
https://twitter.com/summerbrennan/status/800816425057341440
https://twitter.com/joemacare/status/800817149895905280
https://twitter.com/Vanessid/status/800817431627251712
https://twitter.com/sparksjls/status/800819554981212160
https://twitter.com/levendowski/status/800820929928560640
https://twitter.com/cascadiawillem/status/800821256190771200
https://twitter.com/queerbirdnerd/status/800822973078892549
https://twitter.com/malki/status/800824327570538497
https://twitter.com/mjg59/status/800826894325202946
https://twitter.com/JohnDuda/status/800827129252364291
https://twitter.com/ryanpitts/status/800829470047289344
https://twitter.com/MinovskyArticle/status/800829751069999105
https://twitter.com/DavidColeGtown/status/800830222228738048
https://twitter.com/JWMason1/status/800831233341136897
https://twitter.com/HeerJeet/status/800831872808861697
https://twitter.com/umairh/status/800832364398002176
https://twitter.com/waxy/status/800836178454855691
https://twitter.com/Voldemort4Mayor/status/800836899837542404
https://twitter.com/PixelRickie/status/800836936743075841
https://twitter.com/sarahwhelmed/status/800837399303647237
https://twitter.com/cnqmdi/status/800837894956908544
https://twitter.com/nntaleb/status/800838839942205443
https://twitter.com/leashless/status/800838847705862144
https://twitter.com/prisonculture/status/800839258596462592
https://twitter.com/fchollet/status/800839790480363521
https://twitter.com/miniver/status/800840242622119936
https://twitter.com/delight_monger/status/800840388512620544
https://twitter.com/prisonculture/status/800841193240358912
https://twitter.com/prisonculture/status/800841697726894080
https://twitter.com/AAIHS/status/800841977373818880
https://twitter.com/zunguzungu/status/800842187881619456
https://twitter.com/spring_el/status/800842249625997312
https://twitter.com/PaulLewis/status/800842977123782656
https://twitter.com/harrisj/status/800843178878312449
https://twitter.com/harrisj/status/800843387574177792
https://twitter.com/Wolven/status/800843753883914240
https://twitter.com/janeosanders/status/800844649107701760
https://twitter.com/Pinboard/status/800844930570555392
https://twitter.com/miniver/status/800846649761218561
https://twitter.com/tezcatlipoca/status/800847180231688192
https://twitter.com/ubiquity75/status/800848413029896192
https://twitter.com/lifewinning/status/800849589473517568
https://twitter.com/hautepop/status/800849753290444800
https://twitter.com/MuslimIQ/status/800853994046271488
https://twitter.com/jongold/status/800862562296336384
https://twitter.com/jessevondoom/status/800863722088448002
https://twitter.com/futurebird/status/800787825302061056
https://twitter.com/futurebird/status/800788036774690817
https://twitter.com/ShaunKing/status/800788493119066112
https://twitter.com/TheSoundDefense/status/800788581379936256
https://twitter.com/NateMing/status/800788721687621632
https://twitter.com/drewesthaus/status/800788893796732930
https://twitter.com/katecrawford/status/800789503271047168
https://twitter.com/jessevondoom/status/800789556236795904
https://twitter.com/DeborahGraywine/status/800789747006246914
https://twitter.com/samim/status/800789778337763329
https://twitter.com/samim/status/800791152249212928
https://twitter.com/evacide/status/800791157538050048
https://twitter.com/judithd/status/800791160331509760
https://twitter.com/TheLitCritGuy/status/800791233866166272
https://twitter.com/magicbeans/status/800791452041158656
https://twitter.com/kombiz/status/800791593649324032
https://twitter.com/tressiemcphd/status/800792170651418624
https://twitter.com/TUSK81/status/800792549124231168
https://twitter.com/XipiterSec/status/800792571098251264
https://twitter.com/derekwillis/status/800793135408447488
https://twitter.com/tressiemcphd/status/800794549991997442
https://twitter.com/courtinnovation/status/800794667386142720
https://twitter.com/courtinnovation/status/800794667386142720
https://twitter.com/surlyurbanist/status/800796814739804160
https://twitter.com/peterwsinger/status/800797434259509248
https://twitter.com/plussone/status/800797878801207296
https://twitter.com/electionland/status/800798458915524608
https://twitter.com/audreywatters/status/800799782239277056
https://twitter.com/zeynep/status/800801825846870017
https://twitter.com/FreeLawProject/status/800802417436569600
https://twitter.com/radfagg/status/800802531400105984
https://twitter.com/RonWyden/status/800802627059585030
https://twitter.com/prisonculture/status/800802745464786948
https://twitter.com/Horse_Crimes/status/800802819720839168
https://twitter.com/zeynep/status/800802909470543872
https://twitter.com/dakami/status/800803333720018945
https://twitter.com/_SecurityFirst/status/800803514926542848
https://twitter.com/TomSugrue/status/800804174363525120
https://twitter.com/mister_borogove/status/800804231905054721
https://twitter.com/mister_borogove/status/800804507928051712
https://twitter.com/OJutel/status/800805269143851008
https://twitter.com/KevinCarson1/status/800806873335144449
https://twitter.com/SenSanders/status/800807231449169920
https://twitter.com/borzou/status/800807508625526784
https://twitter.com/carlacasilli/status/800807758786220032
https://twitter.com/Interdome/status/800807937019027457
https://twitter.com/Interdome/status/800808344097210369
https://twitter.com/Eclectablog/status/800338989731446784
https://twitter.com/JustSchmeltzer/status/800363859060125696
https://twitter.com/thesarahhunt/status/800397865474355200
https://twitter.com/AlexSteffen/status/800402070159257600
https://twitter.com/AlexSteffen/status/800403340882427904
https://twitter.com/robreiner/status/800516953961959424
https://twitter.com/Chronotope/status/800533359495643136
https://twitter.com/AdamParkhomenko/status/800534977142280193
https://twitter.com/OaklandElle/status/800645469080731648
https://twitter.com/DRMacIver/status/800646611462459392
https://twitter.com/Asher_Wolf/status/800648410671915008
https://twitter.com/SoffiyahElijah/status/800664815538700288
https://twitter.com/PostRoz/status/800694688844017664
https://twitter.com/fawfulfan/status/800702370292371456
https://twitter.com/nkjemisin/status/800709646558367744
https://twitter.com/tinaissa/status/800711944109862912
https://twitter.com/blprnt/status/800741307228491776
https://twitter.com/CaseyG/status/800741770107592704
https://twitter.com/anne_theriault/status/800748091854950402
https://twitter.com/asthesparksfly/status/800760957622484992
https://twitter.com/speechboy71/status/800762912923156481
https://twitter.com/doriantaylor/status/800765623332540416
https://twitter.com/sarahkendzior/status/800768426402664448
https://twitter.com/HeardFC/status/800768981661585409
https://twitter.com/mateagold/status/800777798134566912
https://twitter.com/MazMHussain/status/800778249483812866
https://twitter.com/jacremes/status/800780273801687040
https://twitter.com/cashmusic/status/800780285373648896
https://twitter.com/jbouie/status/800782968482570241
https://twitter.com/navahw/status/800783124141580288
https://twitter.com/Interdome/status/800784002432962561
https://twitter.com/AngieCoiro/status/800784600712679428
https://twitter.com/robyncaplan/status/800784984919437312
https://twitter.com/vogon/status/800785255217016832
https://twitter.com/OaklandElle/status/800787060688764928
https://twitter.com/HalpernAlex/status/800787225642340356
https://twitter.com/suzettesmith/status/800787550218555401

#+END_SRC

What can I say about this data? 

Its transformation should yield a set --- duplicates don't mean anything. 

What do the 'likes' represent? Well this was a pretty serious Nazi week after the election, so the vast majority represent me saving reports, analyses, and recommended actions to tkae in the face of less than 70 days to inauguration. Of those, some of them are threads that represent a conversation's worth of information that I would like to pass on and/or respond to; others are all the way to suggestions for action on getting faithless electors to do their job and not elect someone who is flaunting norms and laws left and right, someone for whom there may be some credible evidence that there was hacks and fraud and idk what else; there are templates and lists for how and who to call to resist, to #NonServiam; some are mere inspiration. Of the rest, there are "I see you" faves that need nothing further but could be recorded as an instance of human feelings between humans, you monster; there are pictures and comics and such that are of brief 'heh' or are of use in the ol' emergency GIFs folder; there are books to order and read, there are connections between the national scene and the environmental racism at the Flint or Standing Rock level...

I mean really, it's a fucking mess, because things are a fucking mess. But it doesn't help to just stare at the freight train. I'm trying to turn these things into collected data. I'm trying to build a Global Frequency here, or at least one node in that sum of frequencies. 

** The Interface

I need to be able to glance at and classify these links quickly, essentially flipping them as little index cards of meaning into piles, so that I can then address each pile in its time. Think of it as a defragging process: putting disparate informations into blocks, so that the blocks may be read more efficiently. Splitting into separate processes, then: assembling blocks for later use, retrieving blocks for a use for now, and maybe it's not so much a process as a display, selecting which block is right for right now. 


*** Tweet component

 tweet
   user
   link
   text
   tag-field
   tag


 #+BEGIN_SRC clojure

   (defc tweet [{:keys [user id]}]
     "A simple view of a tweet that you can click and read using usual browser, and that you can add tags to."
     [:div.tweet
      [:span.user user]
      [:span.tweet-link [:a {:href (str "https://twitter.com/" user "/status/" id)} "follow link"]]
      [:span.tag-field "first tag, second tag"]])

 #+END_SRC

 This is not great. You'll want to handle the tag-field separately, so that you can do the autocomplete at some point. 

 #+BEGIN_SRC clojure

   (defc tag-field [tags]
     "Takes a possibly empty set of tags, will eventually have autocomplete."
     [:input {:type "text" :value (clojure.string/join tags " ")}])

 #+END_SRC
  
 (Surely there's a nice React autocomplete out there, but let's build our own stuff as much as possible rather than getting wrapped up in interoperating with other components.)

 You'll also want to aggregate.

 #+BEGIN_SRC clojure

   (defc feed [items]
     "A collection of potentially salient items that the user should review."
     (map tweet items))

 #+END_SRC








** Server-side
   
It would be nice to be able to, say, get at your favorites automatically, or get the full text of a tweet rather than the messy unescaped monstrosity that gets saved into the 'description/extended' fields in pinboard. You also want to be able to do some kind of social sorting around these things. 

Alas, OAuth was invented to make the Internet not fun. (The other thing invented to make the Internet not fun is the CORS policy but that one I figured out -- roughly, giving clients read privileges is too dangerous so, you have to ask a server that you own to make the request because it's more onerous or something. 

Luckily there exist examples for authenticating with Twitter. Let's use a blog post as an example and see how far we get. 

http://nerd.kelseyinnis.com/blog/2014/05/06/talking-to-yourself-a-twitter-bot-in-clojure-by-a-total-newb/

[x] declare dependency in project.clj

...hm, then i read the post and it's more a CLI thing, with a main and stuff. Still, keep it open. But, let's look at the twitter-api library, and that OAuth lib example as a secondary if needed.





** haha you have no server
Oh yeah. I'll have to tell figwheel about the =:ring-handler=.
https://github.com/bhauman/lein-figwheel/wiki/Configuration-Options
I'm going to proceed under the assumption that I don't even know HOW to make something too complicated for this option. 

* More links as input for the system and/or jobs

http://ocrjournal.bigcartel.com/product/ocr-journal-002
http://www.larousse.fr/encyclopedie/data/images/1314227-Ob%C3%A9ir_cest_trahir_D%C3%A9sob%C3%A9ir_cest_servir.jpg
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=tsne%20word2vec
https://www.google.com/search?q=word2vec%20tsne%20python%20rest#safe=off&q=word2vec+tsne+rest+api
https://www.google.com/search?q=word2maps
http://blog.yhat.com/posts/words2map.html
https://github.com/overlap-ai/words2map
http://overlap.ai/
https://www.yhat.com/jobs
http://blog.yhat.com/posts/words2map.html
https://www.yhat.com/
http://hen-drik.de/pub/Heuer%20-%20word2vec%20-%20From%20theory%20to%20practice.pdf
http://cilvr.nyu.edu/lib/exe/fetch.php?media=deeplearning:2016:laurens.pdf
https://www.tensorflow.org/versions/r0.11/tutorials/word2vec/index.html
https://www.google.com/search?q=word2vec%20flask
https://www.snip2code.com/Snippet/913943/Flask---gensim-word2vec
https://github.com/quhfus/DoSeR/wiki/Word2Vec-Rest-Server
https://github.com/3Top/word2vec-api/blob/master/word2vec-api.py
https://gist.github.com/joegle/b82d70b0d581dc4609e4
** Of Especial Note
http://blog.yhat.com/posts/words2map.html

Words2map is kinda what I'm trying to do, I might ust be able to use their shit, but also, it makes sense to apply to this place since they are trying to overlap passions, i.e., they are doing topic modeling and I could help with that or at least have some opinions about it. 
